<?php

function spinoff_field_info_alter(&$info) {
  foreach ($info as $field_type => &$field_type_info) {
    $field_type_info += array('instance_settings' => array());
    $field_type_info['instance_settings'] += array(
      'spinoff_arg_name' => '',
    );
  }
}

function spinoff_form_field_ui_field_edit_form_alter(&$form, &$form_state, $form_id) {
  $instance = $form['#instance'];
  if ($instance['entity_type'] == 'node' && !$form['#field']['locked']) {
    $form['instance']['settings']['spinoff_arg_name'] = array(
      '#type' => 'textfield',
      '#title' => t('Command Line Argument Name'),
      '#description' => t('Please include dashes'),
      '#default_value' => '',
      '#weight' => 9999,
    );
  }
}